---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-k8s
  template:
    metadata:
      labels:
        app: my-app-k8s
    spec:
      containers:
        - image: xjl00/example-go-k8s:0.0.10
          name: example-go-k8s
          ports:
            - containerPort: 8080