name: ci

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            xjl00/example-go-k8s
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }},
            ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/example-go-k8s:${{ steps.meta.outputs.tags }}
          # Set up additional parameters as needed for GitHub Packages
          labels: org.opencontainers.image.title=My Image Name
          # Add other metadata as needed for GitHub Packages
      - name: Login to GitHub Packages
        run: echo "${{ secrets.CONTAINER_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to GitHub Packages
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/example-go-k8s:${{ steps.meta.outputs.tags }}